# Generated by Django 5.0.2 on 2024-03-12 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='batcore_images')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batcore.categories')),
            ],
        ),
    ]
